version: "3.5"

services:
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./.docker/nginx/logs/:/var/log/server/
      - ./app:/var/www/app
    restart: on-failure
    tty: true
    depends_on:
      - php

  mysql:
    container_name: mysql
    build:
        context: ./.docker/mysql
        dockerfile: Dockerfile
    ports:
        - "3306:3306"
    restart: on-failure
    volumes:
        - ./.docker/mysql/data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  php:
    container_name: php
    build:
      context: .docker/php7.4
      dockerfile: Dockerfile
      args:
        DOCKER_ENV: ${APP_ENV}
        UID: ${UID}
        GID: ${GID}
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    env_file: .env
    restart: on-failure
    tty: true
    links:
      - mysql
