version: "3.5"

services:
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs/:/var/log/server/
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ../app:/var/www/app
    restart: on-failure
    tty: true
    depends_on:
      - php

  mysql:
    container_name: mysql
    build:
        context: ../
        dockerfile: .docker/mysql/Dockerfile
    ports:
        - "3306:3306"
    restart: on-failure
    volumes:
        - ./mysql/data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  php:
    container_name: php
    build:
      context: ../
      dockerfile: .docker/php7.4/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    working_dir: /var/www/app
    volumes:
      - ../app:/var/www/app
    env_file: .env
    restart: on-failure
    tty: true
    links:
      - mysql
